title: Minjeong Cho # your name (or website title) here
logo: "/images/minjeong.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  I’m a research data scientist passionate about building machine learning and statistical forecasting models. 
  <br><br>
  I’m excited to combine my scientific domain knowledge of energy, fluids, and heat with my data science skills to solve real-world problems.
  <br><br>
  <a href="https://www.linkedin.com/in/minjeong-cho/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
